Run `yarn dedupe` on the ui lockfile
Note that I had to force `get-intrinsic` to resolve to 1.3.0. Without
that resolution, we pull 1.3.1 and eslint 7 misparses the
`async-function` dependency that comes with that bump. Which ends up
with issues like this:

```
Oops! Something went wrong! :(

ESLint: 7.32.0

/builds/worker/checkouts/taskcluster/ui/node_modules/async-function/require.mjs:1
(function (exports, require, module, __filename, __dirname) { import getAsyncFunction from './index.js';
                                                              ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:117:7)
    at NativeCompileCache._moduleCompile (/builds/worker/checkouts/taskcluster/ui/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/builds/worker/checkouts/taskcluster/ui/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object..js (node:internal/modules/cjs/loader:1961:10)
    at Module.load (node:internal/modules/cjs/loader:1553:32)
    at Module._load (node:internal/modules/cjs/loader:1355:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.require (node:internal/modules/cjs/loader:1576:12)
    at require (/builds/worker/checkouts/taskcluster/ui/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/builds/worker/checkouts/taskcluster/ui/node_modules/get-intrinsic/index.js:154:24)
```

This resolution can be removed when we move off of eslint