Don't let generic-worker-standalone chown the bind mounted config
Generic worker likes to chown and chmod its config on start which is all
fine and dandy until it's a file that is bind mounted in its container
and it chowns the config to a user that isn't you. Then it breaks git by
always creating a diff (since the mode of the file changes) and git
breaks because it sees the change but can't read the file anymore.

```
error: open("docker/generic-worker-config.json"): Permission denied
fatal: cannot hash docker/generic-worker-config.json
```

This has annoyed me one too many times. Turns out that
generic-worker-static was already doing something similar for
worker-runner's config since #8520 (specifically
06c28e08df4bf1f087a64dbb2ce2f425270db1bc even if it doesn't mention it
at all). I just copy/pasted the solution with
`s/worker-runner/generic-worker` since it's correct in this case too.