Don't use `Object.prototype` builtin methods
This is very easy to misuse and introduce bugs because once again,
javascript is showing how awesome it is at not being able to distinguish
between a builtin method and an object attribute. So the following happens:

```
> {}.hasOwnProperty("bar")
false
> {"hasOwnProperty": 1}.hasOwnProperty("bar")
Uncaught TypeError: {(intermediate value)}.hasOwnProperty is not a function
```

All changes in this commit are actually "false positives" reported by
biome because `Object.prototype.hasOwnProperty.call` is already safe in
that regard. But we definitely want to keep that lint and the result is
a lot more readable anyway.

Fixes biome's noPrototypeBuiltins lint